use std::collections::HashMap;

use super::macros::keymap;
use super::{KeyTrie, Mode};
use helix_core::hashmap;

pub fn default() -> HashMap<Mode, KeyTrie> {
    let normal = keymap!({ "Normal mode"
        "y" | "left" => move_char_left,
        "n" | "down" => move_visual_line_down,
        "e" | "up" => move_visual_line_up,
        "o" | "right" => move_char_right,
        "Y" => extend_to_first_nonwhitespace,
        "O" => extend_to_line_end,
        "pageup" => page_up,
        "pagedown" => page_down,
        "home" => goto_file_start,
        "end" => goto_last_line,

        "t" => find_till_char,
        "T" => till_prev_char,

        "h" => find_next_char,
        "H" => find_prev_char,

        "r" => replace,
        "," =>  repeat_last_motion,
        // "R" => replace_with_yanked,

        "'" => switch_case,
        "`" => switch_to_lowercase,
        "\"" => switch_to_uppercase,

        // "home" => goto_line_start,
        // "end" => goto_line_end,

        "w" => move_next_word_start,
        "W" => move_next_long_word_start,

        "b" => move_prev_word_start,
        "B" => move_prev_long_word_start,
        "N" => move_next_word_end,
        "E" => move_next_long_word_end,
        "v" => select_mode,
        // "G" => goto_line,
        "G" => goto_word,
        "g" => { "Goto"
            "s" => goto_file_start,
            "e" => goto_last_line,
            "|" => goto_column,
            "f" => goto_file,
            "y" => goto_first_nonwhitespace,
            "Y" => goto_line_start,
            "o" => goto_line_end,
            "d" => goto_definition,
            "D" => goto_declaration,
            "t" => goto_type_definition,
            "r" => goto_reference,
            "R" => select_references_to_symbol_under_cursor,
            "i" => goto_implementation,
            "l" => goto_last_accessed_file,
            "m" => goto_last_modified_file,
            "n" => goto_next_buffer,
            "p" => goto_previous_buffer,
            "." => goto_last_modification,
            "w" => goto_word,
        },
        ":" => command_mode,

        "i" => insert_mode,
        "I" => insert_at_line_start,
        "a" => append_mode,
        "A" => insert_at_line_end,
        "l" => open_below,
        "L" => open_above,

        "d" => delete_selection,
        // "A-d" => delete_selection_noyank,
        "c" => change_selection,
        // "A-c" => change_selection_noyank,

        "C" => copy_selection_on_next_line,
        // "A-C" => copy_selection_on_prev_line,


        "s" => select_regex,
        "A-s" => split_selection_on_newline,
        // "A-minus" => merge_selections,
        // "A-_" => merge_consecutive_selections,
        "S" => split_selection,
        ";" => collapse_selection,
        "tab" => flip_selections,
        "S-tab" => reverse_selection_contents,
        // "A-o" | "A-up" => expand_selection,
        // "A-i" | "A-down" => shrink_selection,
        // "A-I" | "A-S-down" => select_all_children,
        // "A-p" | "A-left" => select_prev_sibling,
        // "A-n" | "A-right" => select_next_sibling,
        // "A-e" => move_parent_node_end,
        // "A-b" => move_parent_node_start,
        // "A-a" => select_all_siblings,

        "%" => select_all,
        "x" => extend_line_below,
        "X" => extend_to_line_bounds,
        // "A-x" => shrink_to_line_bounds,

        "M" => match_brackets,
        "m" => { "Match"
            "m" => match_brackets,
            "s" => surround_add,
            "r" => surround_replace,
            "d" => surround_delete,
            "a" => select_textobject_around,
            "i" => select_textobject_inner,
        },
        "[" => { "Left bracket"
            "d" => goto_prev_diag,
            "D" => goto_first_diag,
            "g" => goto_prev_change,
            "G" => goto_first_change,
            "f" => goto_prev_function,
            "t" => goto_prev_class,
            "a" => goto_prev_parameter,
            "c" => goto_prev_comment,
            "e" => goto_prev_entry,
            "T" => goto_prev_test,
            "p" => goto_prev_paragraph,
            "space" => add_newline_above,
        },
        "]" => { "Right bracket"
            "d" => goto_next_diag,
            "D" => goto_last_diag,
            "g" => goto_next_change,
            "G" => goto_last_change,
            "f" => goto_next_function,
            "t" => goto_next_class,
            "a" => goto_next_parameter,
            "c" => goto_next_comment,
            "e" => goto_next_entry,
            "T" => goto_next_test,
            "p" => goto_next_paragraph,
            "space" => add_newline_below,
        },

        "/" => search,
        "?" => rsearch,
        "f" => search_next,
        "F" => search_prev,
        "*" => search_selection_detect_word_boundaries,
        // "A-*" => search_selection,

        "u" => undo,
        "U" => redo,
        // "A-u" => earlier,
        // "A-U" => later,

        "k" => yank,
        // yank_all
        "p" => paste_after,
        // paste_all
        "P" => paste_before,
        "C-p" => replace_with_yanked,

        "z" => record_macro,
        "Z" => replay_macro,

        ">" => indent,
        "<" => unindent,
        "=" => format_selections,
        "j" => join_selections,
        "J" => join_selections_space,
        // "K" => keep_selections,
        // "A-K" => remove_selections,

        "esc"  => unruly_normal_mode_or_keep_primary_selection,
        // "esc" => norkeep_primary_selection,
        "C-esc" => keep_selections,
        "backspace" => remove_primary_selection,
        "C-backspace" => remove_selections,

        // "q" => record_macro,
        // "Q" => replay_macro,

        "&" => align_selections,
        "_" => goto_next_diag,
        "-" => goto_prev_diag,
        "R" => hover,

        "(" => rotate_selections_backward,
        ")" => rotate_selections_forward,
        // "A-(" => rotate_selection_contents_backward,
        // "A-)" => rotate_selection_contents_forward,

        // "A-:" => ensure_selections_forward,

        // "esc" => normal_mode,
        // "C-b" | "pageup" => page_up,
        // "C-f" | "pagedown" => page_down,
        // "C-u" => page_cursor_half_up,
        // "C-d" => page_cursor_half_down,
        "C-d" => goto_definition,
        "C-r" => rename_symbol,
        "C-m" =>  save_selection,
        "C-j" => file_picker,
        // "C-m" => wonly,
        // "C-j" => file_picker,

        "C-w" => { "Window"
            "C-w" | "w" => rotate_view,
            "C-t" | "t" => transpose_view,
            "C-h" | "h" => hsplit,
            "C-s" | "s" => vsplit,
            "C-x" | "x" => wclose,
            "C-f" | "f" => wonly,
            "C-y" | "y" | "left" => jump_view_left,
            "C-n" | "n" | "down" => jump_view_down,
            "C-e" | "e" | "up" => jump_view_up,
            "C-o" | "o" | "right" => jump_view_right,
            "Y" => swap_view_left,
            "N" => swap_view_down,
            "E" => swap_view_up,
            "O" => swap_view_right,
        },
        "C-h" => hsplit,
        "C-s" => vsplit,
        "C-x" => wclose,
        "C-f" => wonly,
        "C-y" => jump_view_left,
        "C-n" => jump_view_down,
        "C-e" => jump_view_up,
        "C-o" => jump_view_right,

        // move under <space>c
        "C-c" => toggle_comments,

        // z family for save/restore/combine from/to sels from register

         "}" => jump_forward, // tab == <C-i>
        "{" => jump_backward,
        // "C-s" => save_selection,

        "space" => { "Space"
            "f" => file_picker,
            "F" => file_picker_in_current_directory,
            "e" => file_explorer,
            "E" => file_explorer_in_current_buffer_directory,
            "b" => buffer_picker,
            "j" => jumplist_picker,
            "s" => symbol_picker,
            "S" => workspace_symbol_picker,
            "d" => diagnostics_picker,
            "D" => workspace_diagnostics_picker,
            // "g" => changed_file_picker,
            "a" => code_action,
            "l" => last_picker,
            "G" => { "Debug (experimental)" sticky=true
                "l" => dap_launch,
                "r" => dap_restart,
                "b" => dap_toggle_breakpoint,
                "c" => dap_continue,
                "h" => dap_pause,
                "i" => dap_step_in,
                "o" => dap_step_out,
                "n" => dap_next,
                "v" => dap_variables,
                "t" => dap_terminate,
                "C-c" => dap_edit_condition,
                "C-l" => dap_edit_log,
                "s" => { "Switch"
                    "t" => dap_switch_thread,
                    "f" => dap_switch_stack_frame,
                    // sl, sb
                },
                "e" => dap_enable_exceptions,
                "E" => dap_disable_exceptions,
            },
            "/" => global_search,
            "?" => command_palette,
        },
        "K" => { "Kopy"
            "d" => delete_selection_noyank,
            "c" => change_selection_noyank,
            "k" => yank_to_clipboard,
            "K" => yank_main_selection_to_clipboard,
            "p" => paste_clipboard_after,
            "P" => paste_clipboard_before,
            "r" => replace_selections_with_clipboard,
       },
       "V" => align_view_top,
        "$" => { "Align"
            "$" | "c" | "m" => align_view_center,
            "t" => align_view_top,
            "b" => align_view_bottom,
            // "m" => align_view_middle,
            // "pageup" => page_up,
            // "pagedown" => page_down,
            // "C-u" | "e" => page_cursor_half_up,
            // "C-d" | "n" => page_cursor_half_down,

        },
        "#" => { "Scroll" sticky=true
            "e" | "up" => scroll_up,
            "n" | "down" => scroll_down,
            "E" => page_cursor_half_up,
            "N" => page_cursor_half_down,
        },
        "|" => { "Shell"
            "p" => shell_pipe,
            "P" => shell_pipe_to,
            "i" => shell_insert_output,
            "a" => shell_append_output,
            "k" => shell_keep_pipe,
        },
        "@" => select_register,
        // "|" => shell_pipe,
        // "A-|" => shell_pipe_to,
        // "!" => shell_insert_output,
        // "A-!" => shell_append_output,
        // "$" => shell_keep_pipe,
        "C-z" => suspend,

        // "C-a" => increment,
        // "C-x" => decrement,
    });
    let mut select = normal.clone();
    select.merge_nodes(keymap!({ "Select mode"
        "y" | "left" => extend_char_left,
        "n" | "down" => extend_visual_line_down,
        "e" | "up" => extend_visual_line_up,
        "o" | "right" => extend_char_right,

        "w" => extend_next_word_start,
        "W" => extend_prev_word_start,
        "b" => extend_next_long_word_start,
        "B" => extend_prev_long_word_start,

        // "e" => extend_next_word_end,
        // "E" => extend_next_long_word_end,
        // "A-e" => extend_parent_node_end,
        // "A-b" => extend_parent_node_start,

        "f" => extend_search_next,
        "F" => extend_search_prev,

        "t" => extend_till_char,
        "T" => extend_till_prev_char,

        "h" => extend_next_char,
        "H" => extend_prev_char,

        "Y" => extend_to_line_start,
        "O" => extend_to_line_end,
        "esc" => exit_select_mode,

        "v" => normal_mode,
        "g" => { "Goto"
            "s" => extend_to_file_start,
            "e" => extend_to_last_line,
            "|" => extend_to_column,
            "N" => extend_line_up,
            "E" => extend_line_down,
            "w" => extend_to_word,
        },
    }));
    let insert = keymap!({ "Insert mode"
        "esc" => normal_mode,

        // "C-u" => commit_undo_checkpoint,
        "C-x" => completion,
        "C-r" => insert_register,

        "C-backspace" => delete_word_backward,
        "C-del" => delete_word_forward,
        "C-u" => kill_to_line_start,
        "C-k" => kill_to_line_end,
        "backspace" | "S-backspace" => delete_char_backward,
        "del" => delete_char_forward,
        "ret" => insert_newline,
        "tab" => smart_tab,
        "S-tab" => insert_tab,

        "up" => move_visual_line_up,
        "down" => move_visual_line_down,
        "left" => move_char_left,
        "right" => move_char_right,
        "pageup" => page_up,
        "pagedown" => page_down,
        "home" => goto_line_start,
        "end" => goto_line_end_newline,
    });
    hashmap!(
        Mode::Normal => normal,
        Mode::Select => select,
        Mode::Insert => insert,
    )
}
